### ISSUE TITLE
Friendly error message

### ISSUE THREAD

**Issue by bertrandk** [rangle/serve-webpack-client#3]
When the client attempts to load a file that doesn't exist, all you seem to get is a generic "Error: no such file or directory", followed by a stack trace.

Getting the name of the missing file might be helpful...or a standard 404 maybe?

Ref: https://github.com/rangle/serve-webpack-client/blob/7e417004000ad2ba347f4cf59944085a535188bc/index.js#L41

**Comment by SethDavenport** [comment]
Seems like a reasonable request - do you no longer want it?
